### ISSUE TITLE
 Error: Unable to resolve module ActivityIndicator

### ISSUE THREAD

**Issue by AursorDev** [pradeep1991singh/react-native-image-color-picker#31]
versions:

` 
 "react": "18.2.0",
    "react-native": "0.71.11",
    "react-native-image-color-picker": "^1.0.4",
`

Error: ENOENT: no such file or directory, open 'D:\CodeMore\reactnativeapp\http:\localhost:8081\index.bundle?platform=android&dev=true&minify=false&app=com.reactnativeapp&modulesOnly=false&runModule=true'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at getCodeFrame (D:\CodeMore\reactnativeapp\node_modules\metro\src\Server.js:1018:18)
    at Server._symbolicate (D:\CodeMore\reactnativeapp\node_modules\metro\src\Server.js:1100:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (D:\CodeMore\reactnativeapp\node_modules\metro\src\Server.js:444:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\CodeMore\\reactnativeapp\\http:\\localhost:8081\\index.bundle?platform=android&dev=true&minify=false&app=com.reactnativeapp&modulesOnly=false&runModule=true'
}

**Comment by AursorDev** [comment]
error: Error: Unable to resolve module ActivityIndicator from D:\CodeMore\reactnativeapp\node_modules\react-native-image-color-picker\node_modules\react-native\Libraries\react-native\react-native.js: ActivityIndicator could not be found within the project or in these directories:
  node_modules\react-native-image-color-picker\node_modules\react-native\node_modules
  node_modules\react-native-image-color-picker\node_modules
  node_modules
  28 | const ReactNative = {
  29 |   // Components
> 30 |   get ActivityIndicator() { return require('ActivityIndicator'); },
     |                                             ^
  31 |   get ART() { return require('ReactNativeART'); },
  32 |   get Button() { return require('Button'); },
  33 |   get DatePickerIOS() { return require('DatePickerIOS'); },
    at ModuleResolver.resolveDependency (D:\CodeMore\reactnativeapp\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (D:\CodeMore\reactnativeapp\node_modules\metro\src\node-haste\DependencyGraph.js:260:43)

**Comment by hamda-0** [comment]
> error: Error: Unable to resolve module ActivityIndicator from D:\CodeMore\reactnativeapp\node_modules\react-native-image-color-picker\node_modules\react-native\Libraries\react-native\react-native.js: ActivityIndicator could not be found within the project or in these directories: node_modules\react-native-image-color-picker\node_modules\react-native\node_modules node_modules\react-native-image-color-picker\node_modules node_modules 28 | const ReactNative = { 29 | // Components
> 
> > 30 |   get ActivityIndicator() { return require('ActivityIndicator'); },
> > |                                             ^
> > 31 |   get ART() { return require('ReactNativeART'); },
> > 32 |   get Button() { return require('Button'); },
> > 33 |   get DatePickerIOS() { return require('DatePickerIOS'); },
> > at ModuleResolver.resolveDependency (D:\CodeMore\reactnativeapp\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:162:15)
> > at DependencyGraph.resolveDependency (D:\CodeMore\reactnativeapp\node_modules\metro\src\node-haste\DependencyGraph.js:260:43)
